command: ["node", "index.js"]
env:
  - name: DATABRICKS_HOST
    value: "https://your-workspace-url"
  - name: DATABRICKS_TOKEN
    value: "your-databricks-token"
  - name: SERVING_ENDPOINT
    value: "databricks-claude-sonnet-4"
